In [17]:
import numpy as np 

# First declare our input data as an 4x3 array and the labels as an 4x1 array

In [37]:
# testdata

x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]], dtype = float)
                
y = np.array([[3],
            [5],
            [1],
            [2]], dtype = float)


# normalize input- / output data to a range between 0 and 1

In [38]:
# scale to prevent exploding gradients
scale_x = np.max(x)
scale_y = np.max(y)
x /= scale_x
y /= scale_y

# Define a neural network class which accepts out toy data 

In [39]:
class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 3
        self.outputSize = 1
        self.hiddenSize = 10

        self.W1 = np.random.uniform(0.1,1,[self.inputSize, self.hiddenSize])
        self.W2 = np.random.uniform(0.1,1,[self.hiddenSize, self.outputSize])

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(X, self.W1)             # dot product of X (input) and first weights
        self.z2 = self.sigmoid(self.z)          # use activation function on result
        self.z3 = np.dot(self.z2, self.W2)      # dot product of hidden layer (z2) and weights of hidden layer
        o = self.sigmoid(self.z3)               # use activation function on result
        return o 

    def sigmoid(self, x):
        # activation function 
        return 1/(1+np.exp(-x))

    def sigmoidDerivative(self, x):
        #derivative of sigmoid
        return x * (1 - x)

    def backward(self, X, y, o):
        # backward propgate through network 
        self.o_error = (y - o) # error in output
        self.o_delta = self.o_error*self.sigmoidDerivative(o)   # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.W2.T)             # z2 error: how much our hidden layer weights contributed to output error

        self.W1 += X.T.dot(self.z2_error)* 0.2                  # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta) * 0.2            # adjusting second set (hidden --> output) weights

    def train (self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

In [40]:
# create a new instance of Neural_Network class

NN = Neural_Network()

# now lets train on 600 epochs

for i in xrange(600):
  
  NN.train(x, y)

# check the result    

result = NN.forward(x)

# print result after 600th epoch
print(result*scale_y)

[[ 3.20227505]
 [ 4.4624229 ]
 [ 0.65184742]
 [ 2.17855821]]


In [41]:
# now lets create some test data to see if the network did learn correctly

test = np.array([[1,1,1],
            [0,0,1]], dtype = float)


In [42]:
# print the predicted labels of our test data
result = NN.forward(test)
print(result*scale_y)

[[ 2.17855821]
 [ 3.20227505]]


In [43]:
# now lets print the real labels (values are picked from training data)

label = np.array([[2],[3]], dtype = float)
print(label)

[[ 2.]
 [ 3.]]
