In [1]:
import numpy as np 

# First declare our input data as an 4x3 array and the labels as an 4x1 array

In [2]:
# testdata

x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]], dtype = float)
                
y = np.array([[3],
            [5],
            [1],
            [2]], dtype = float)


# normalize input- / output data to a range between 0 and 1

In [3]:
# scale to prevent exploding gradients
scale_x = np.max(x)
scale_y = np.max(y)
#x /= scale_x
y /= scale_y

In [4]:
def relu(x):
    return np.maximum(x, 0)

def reluPrime(x):
    x[x<0] = 0
    x[x>0] = 1
    return x	

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoidPrime(x):
    return x * (1 - x)

# Define a neural network class which accepts out toy data 

In [5]:
class Neural_Network(object):
	def __init__(self, activation, inputSize, outputSize, hiddenSize):
		#parameters
		self.inputSize = inputSize
		self.outputSize = outputSize
		self.hiddenSize = hiddenSize

		self.W1 = np.random.uniform(0.1,1,[self.inputSize, self.hiddenSize])
		self.W2 = np.random.uniform(0.1,1,[self.hiddenSize, self.outputSize])

	def forward(self, X):
		#forward propagation through our network
		self.z = np.dot(X, self.W1) 			# dot product of X (input) and first set of 3x2 weights
		self.z2 = relu(self.z) 			# activation function
		self.z3 = np.dot(self.z2, self.W2) 		# dot product of hidden layer (z2) and second set of 3x1 weights
		o = relu(self.z3) 				# final activation function
		return o

	def backward(self, X, y, o):
		# backward propgate through network 
		self.o_error = (y - o) # error in output
		self.o_delta = self.o_error*reluPrime(o) 	# applying derivative of sigmoid to error

		self.z2_error = self.o_delta.dot(self.W2.T) 		# z2 error: how much our hidden layer weights contributed to output error

		self.W1 += X.T.dot(self.z2_error)* 0.02 			# adjusting first set (input --> hidden) weights
		self.W2 += self.z2.T.dot(self.o_delta) * 0.02 		# adjusting second set (hidden --> output) weights

	def train (self, X, y):
		o = self.forward(X)
		self.backward(X, y, o)

In [19]:
# create a new instance of Neural_Network class

NN = Neural_Network('relu', 3,1,10)

# now lets train on 600 epochs

for i in xrange(600):
  
  NN.train(x, y)

# check the result    

result = NN.forward(x)

# print result after 600th epoch
print(result*scale_y)

[[ 3.19947171]
 [ 4.8021067 ]
 [ 0.79940606]
 [ 2.19938138]]


In [24]:
# now lets create some test data to see if the network did learn correctly

test = np.array([[1,1,1],
            [0,0,1]], dtype = float)


In [25]:
# print the predicted labels of our test data
result = NN.forward(test)
print(result*scale_y)

[[ 2.24243934]
 [ 3.2514153 ]]


In [26]:
# now lets print the real labels (values are picked from training data)

label = np.array([[2],[3]], dtype = float)
print(label)

[[ 2.]
 [ 3.]]
